export const data = [
    {
        "id": "1",
        "companyName": "GO-AIR",
        "logo": "https://banner2.cleanpng.com/20180509/uwq/avc48p0r6.webp",
        "pdf":"https://pdfobject.com/pdf/sample.pdf",
        "fullName": "GO-AIR PVT LTD",
        "issue-date": "4th - 7th Oct 2022",
        "issue-size": "₹ 3600 Crores",
        "prize-range": "₹ 50-60",
        "min": "50000",
        "invest/qty" : "100 Shares / 5 Lots",
        "listedOn": "7 Oct 22",
        "listedPrice": "₹150",
        "listingGains": "₹10(10.0%)",
        "desciption": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum feugiat eleifend urna, sit amet scelerisque odio molestie ut. Morbi interdum felis neque, vel commodo magna dictum in. Integer sit amet mattis nisi. Aenean imperdiet enim et velit ultrices hendrerit. Donec vitae dui dictum, faucibus ante in, malesuada odio. Nam ac sollicitudin ante. Quisque pharetra, ipsum ut iaculis auctor, elit justo elementum tortor, sit amet malesuada erat lectus at velit. Nullam mollis cursus sem quis ullamcorper. Vestibulum eu condimentum orci. Nam a orci eget elit vehicula consequat at nec neque. Nullam posuere tempus quam, at iaculis turpis consectetur eu. Curabitur bibendum ex felis, nec lobortis ante finibus non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer convallis neque augue, at auctor eros luctus eget. Aenean porttitor elit id magna commodo faucibus. Donec molestie lobortis ipsum aliquam interdum. Phasellus ut orci id sapien aliquet consequat. Duis lobortis nec nibh eu volutpat. Donec blandit ac eros at sagittis. Maecenas placerat vestibulum velit, eget hendrerit nisl finibus a. Praesent id fringilla elit, vitae porttitor eros. Quisque iaculis viverra luctus. Curabitur massa tellus, lacinia ornare orci ut, lobortis ultrices velit. Donec condimentum eget massa eu faucibus. Quisque ornare nulla velit, quis finibus lacus porta in. Sed turpis mauris, commodo a volutpat id, egestas in nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin faucibus ex eget elementum ullamcorper. Vestibulum imperdiet erat ut turpis congue viverra. Morbi lobortis bibendum metus vitae dapibus. Cras pharetra pulvinar mattis. Vestibulum pellentesque augue diam, ut eleifend arcu ultricies nec. Quisque at felis placerat, imperdiet ligula sed, dictum nulla. Donec sollicitudin iaculis vehicula. Sed ullamcorper, turpis a egestas aliquet, enim nunc semper massa, vitae congue eros mi tempus sem. Mauris orci ex, vehicula id dui a, fringilla volutpat turpis. Phasellus maximus luctus viverra. Etiam viverra lacinia mauris, eget sollicitudin orci tincidunt a. In et sem id lacus tincidunt lacinia. Sed luctus neque fermentum libero ultrices, dapibus luctus magna aliquet. Aenean pretium, tellus elementum egestas auctor, ligula nisi molestie dui, molestie faucibus ex purus sit amet purus.",
        "timeline": [
            {"title": "Bidding starts", "date":"12 Dec 2023", "completed":"true"},
            {"title": "Bidding ends", "date":"15 Dec 2023", "completed":"true"},
            {"title": "Allotment finalization", "date":"18 Dec 2023", "completed":"true"},
            {"title": "Refund initiation", "date":"18 Dec 2023", "completed":"true"},
            {"title": "Demat transfer", "date":"18 Dec 2023", "completed":"true"},
            {"title": "Listing date", "date":"21 Dec 2023","completed":"true"},
        ]
    },
    {
        "id": "2",
        "companyName": "BAJAJ ENERGY",
        "logo": "https://bajajenergy.com/bajajenergy_assets/s3fs-public/images/Bajaj%20Energy_300x118_Png.png",
        "pdf":"https://pdfobject.com/pdf/sample.pdf",
        "fullName": "Bajaj Energy limited",
        "issue-date": "4th - 7th Oct 2022",
        "issue-size": "₹ 3600 Crores",
        "prize-range": "₹ 50-60",
        "min": "50000",
        "invest/qty" : "100 Shares / 5 Lots",
        "listedOn": "7 Oct 22",
        "listedPrice": "₹150",
        "listingGains": "₹10(10.0%)",
        "desciption": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum feugiat eleifend urna, sit amet scelerisque odio molestie ut. Morbi interdum felis neque, vel commodo magna dictum in. Integer sit amet mattis nisi. Aenean imperdiet enim et velit ultrices hendrerit. Donec vitae dui dictum, faucibus ante in, malesuada odio. Nam ac sollicitudin ante. Quisque pharetra, ipsum ut iaculis auctor, elit justo elementum tortor, sit amet malesuada erat lectus at velit. Nullam mollis cursus sem quis ullamcorper. Vestibulum eu condimentum orci. Nam a orci eget elit vehicula consequat at nec neque. Nullam posuere tempus quam, at iaculis turpis consectetur eu. Curabitur bibendum ex felis, nec lobortis ante finibus non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer convallis neque augue, at auctor eros luctus eget. Aenean porttitor elit id magna commodo faucibus. Donec molestie lobortis ipsum aliquam interdum. Phasellus ut orci id sapien aliquet consequat. Duis lobortis nec nibh eu volutpat. Donec blandit ac eros at sagittis. Maecenas placerat vestibulum velit, eget hendrerit nisl finibus a. Praesent id fringilla elit, vitae porttitor eros. Quisque iaculis viverra luctus. Curabitur massa tellus, lacinia ornare orci ut, lobortis ultrices velit. Donec condimentum eget massa eu faucibus. Quisque ornare nulla velit, quis finibus lacus porta in. Sed turpis mauris, commodo a volutpat id, egestas in nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin faucibus ex eget elementum ullamcorper. Vestibulum imperdiet erat ut turpis congue viverra. Morbi lobortis bibendum metus vitae dapibus. Cras pharetra pulvinar mattis. Vestibulum pellentesque augue diam, ut eleifend arcu ultricies nec. Quisque at felis placerat, imperdiet ligula sed, dictum nulla. Donec sollicitudin iaculis vehicula. Sed ullamcorper, turpis a egestas aliquet, enim nunc semper massa, vitae congue eros mi tempus sem. Mauris orci ex, vehicula id dui a, fringilla volutpat turpis. Phasellus maximus luctus viverra. Etiam viverra lacinia mauris, eget sollicitudin orci tincidunt a. In et sem id lacus tincidunt lacinia. Sed luctus neque fermentum libero ultrices, dapibus luctus magna aliquet. Aenean pretium, tellus elementum egestas auctor, ligula nisi molestie dui, molestie faucibus ex purus sit amet purus.",
        "timeline": [
            {"title": "Bidding starts", "date":"12 Dec 2023", "completed":"true"},
            {"title": "Bidding ends", "date":"15 Dec 2023", "completed":"true"},
            {"title": "Allotment finalization", "date":"18 Dec 2023", "completed":"true"},
            {"title": "Refund initiation", "date":"18 Dec 2023", "completed":"true"},
            {"title": "Demat transfer", "date":"18 Dec 2023", "completed":"true"},
            {"title": "Listing date", "date":"21 Dec 2023","completed":"true"},
        ]
    },
    {
        "id": "3",
        "companyName": "OYO",
        "logo": "https://seeklogo.com/images/O/oyo-rooms-logo-6C301512FE-seeklogo.com.png",
        "pdf":"https://pdfobject.com/pdf/sample.pdf",
        "fullName": "OYO Private Limited",
        "issue-date": "To be annouced",
        "issue-size": "₹ 3600 Crores",
        "prize-range": "₹ 50-60",
        "min": "50000",
        "invest/qty" : "100 Shares / 5 Lots",
        "listedOn": "7 Oct 22",
        "listedPrice": "₹150",
        "listingGains": "₹10(10.0%)",
        "desciption": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum feugiat eleifend urna, sit amet scelerisque odio molestie ut. Morbi interdum felis neque, vel commodo magna dictum in. Integer sit amet mattis nisi. Aenean imperdiet enim et velit ultrices hendrerit. Donec vitae dui dictum, faucibus ante in, malesuada odio. Nam ac sollicitudin ante. Quisque pharetra, ipsum ut iaculis auctor, elit justo elementum tortor, sit amet malesuada erat lectus at velit. Nullam mollis cursus sem quis ullamcorper. Vestibulum eu condimentum orci. Nam a orci eget elit vehicula consequat at nec neque. Nullam posuere tempus quam, at iaculis turpis consectetur eu. Curabitur bibendum ex felis, nec lobortis ante finibus non. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer convallis neque augue, at auctor eros luctus eget. Aenean porttitor elit id magna commodo faucibus. Donec molestie lobortis ipsum aliquam interdum. Phasellus ut orci id sapien aliquet consequat. Duis lobortis nec nibh eu volutpat. Donec blandit ac eros at sagittis. Maecenas placerat vestibulum velit, eget hendrerit nisl finibus a. Praesent id fringilla elit, vitae porttitor eros. Quisque iaculis viverra luctus. Curabitur massa tellus, lacinia ornare orci ut, lobortis ultrices velit. Donec condimentum eget massa eu faucibus. Quisque ornare nulla velit, quis finibus lacus porta in. Sed turpis mauris, commodo a volutpat id, egestas in nisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin faucibus ex eget elementum ullamcorper. Vestibulum imperdiet erat ut turpis congue viverra. Morbi lobortis bibendum metus vitae dapibus. Cras pharetra pulvinar mattis. Vestibulum pellentesque augue diam, ut eleifend arcu ultricies nec. Quisque at felis placerat, imperdiet ligula sed, dictum nulla. Donec sollicitudin iaculis vehicula. Sed ullamcorper, turpis a egestas aliquet, enim nunc semper massa, vitae congue eros mi tempus sem. Mauris orci ex, vehicula id dui a, fringilla volutpat turpis. Phasellus maximus luctus viverra. Etiam viverra lacinia mauris, eget sollicitudin orci tincidunt a. In et sem id lacus tincidunt lacinia. Sed luctus neque fermentum libero ultrices, dapibus luctus magna aliquet. Aenean pretium, tellus elementum egestas auctor, ligula nisi molestie dui, molestie faucibus ex purus sit amet purus.",
        "timeline": [
            {"title": "Bidding starts", "date":"12 Dec 2023", "completed":"true"},
            {"title": "Bidding ends", "date":"15 Dec 2023", "completed":"false"},
            {"title": "Allotment finalization", "date":"18 Dec 2023", "completed":"false"},
            {"title": "Refund initiation", "date":"18 Dec 2023", "completed":"false"},
            {"title": "Demat transfer", "date":"18 Dec 2023", "completed":"false"},
            {"title": "Listing date", "date":"21 Dec 2023","completed":"false"},
        ]
    },
]